
trigger:
- main

variables:
- group: StaticWebToken   # Your deployment token variable group

pool:
  name: 'MyPC-AgentPool'  # Use your self-hosted agent

steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: '.'                     # Path to your static site in the repo
    output_location: ''                   # Leave blank for plain HTML
    azure_static_web_apps_api_token: '$(deployment_token)'
  displayName: 'Deploy to Azure Static Web App'


