# azure-pipelines.yml
trigger:
- main

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent

steps:
# Step 1: Use Node.js (required for React)
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # Specify Node.js version
  displayName: 'Use Node.js 18.x'

# Step 2: Install dependencies
- script: npm install
  displayName: 'Install NPM packages'

# Step 3: Build React app
- script: npm run build
  displayName: 'Build React App'

# Step 4: Copy build folder to staging
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Build to Artifact Staging'

# Step 5: Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_service_connection: 'AzureStaticWebAppConnection'
    app_location: '.'             # Root of repo
    output_location: 'build'      # React build output folder
  displayName: 'Deploy to Azure Static Web App'
