trigger:
- main

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent pool

variables:
- group: AzureSP  # Reference the variable group with SP credentials

# Path to your static app and output
- name: appLocation
  value: "."           # Directory of your static app
- name: outputLocation
  value: "build"       # Build output directory

- name: staticAppName
  value: "Ymy-first-static-site"  # Your Azure Static Web App name
- name: resourceGroup
  value: "my-first-static-site_group"  # Resource group name

steps:
- task: PowerShell@2
  displayName: 'Deploy Static Web App'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Logging in to Azure using service principal..."
      az login --service-principal -u $(azureSPAppId) -p $(azureSPPassword) --tenant $(azureTenantId)

      Write-Host "Building app (if needed)..."
      # Optional: add build commands if using Node.js/React/Vue
      # Example:
      # npm install
      # npm run build

      Write-Host "Deploying static app to Azure Static Web App..."
      az staticwebapp deploy `
        --name $(staticAppName) `
        --resource-group $(resourceGroup) `
        --source-location $(appLocation) `
        --output-location $(outputLocation)

      Write-Host "Deployment completed successfully!"
