trigger:
- main

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted Windows agent

steps:
# Step 1: Build (for static HTML, just a placeholder)
- script: echo "Building static HTML site..."
  displayName: 'Build Step'

# Step 2: Copy files to artifact staging (optional)
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Step 3: Publish artifacts (optional)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Step 4: Deploy to Azure Static Web App using Azure CLI
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureStaticWebAppConnection'  # Your service connection
    scriptType: 'ps'                                  # Windows PowerShell
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Replace with your app name and resource group
      $appName = "my-first-static-site"
      $resourceGroup = "my-first-static-site_group"

      Write-Host "Deploying static HTML to $appName..."
      
      az staticwebapp upload `
        --name $appName `
        --resource-group $resourceGroup `
        --source "$(Build.SourcesDirectory)" `
        --location "Central US" `
        --verbose
  displayName: 'Deploy to Azure Static Web App'
