# azure-pipelines.yml
trigger:
- main   # Runs pipeline on push to 'main'

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent

variables:
  azure_static_web_apps_service_connection: 'AzureStaticWebAppConnection' # Your service connection

steps:

# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'   # Use the Node.js version your React app requires
  displayName: 'Use Node.js 20.x'

# Step 2: Install NPM packages
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'nebula-ui'    # React project folder
  displayName: 'Install NPM packages'

# Step 3: Build React App
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: 'nebula-ui'
  displayName: 'Build React App'

# Step 4: Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_service_connection: '$(azure_static_web_apps_service_connection)'
    app_location: 'nebula-ui'          # React source folder
    output_location: 'nebula-ui/build' # React build folder
  displayName: 'Deploy React App'
