trigger:
- main

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent pool

variables:
  azureSPAppId: $(azureSPAppId)         # Service principal appId
  azureSPPassword: $(azureSPPassword)   # Service principal password (secret)
  azureTenantId: $(azureTenantId)       # Tenant ID
  staticAppName: "YOUR_STATIC_APP_NAME"
  resourceGroup: "YOUR_RESOURCE_GROUP"
  appLocation: "."                      # Directory of your static app
  outputLocation: "build"               # Build output directory

steps:

- task: PowerShell@2
  displayName: 'Deploy Static Web App'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Logging in to Azure using service principal..."
      az login --service-principal -u $(azureSPAppId) -p $(azureSPPassword) --tenant $(azureTenantId)

      Write-Host "Installing dependencies and building app (if needed)..."
      # Add build commands here if your app requires it
      # Example for Node.js: npm install && npm run build

      Write-Host "Deploying static app to Azure Static Web App..."
      az staticwebapp deploy `
        --name $(staticAppName) `
        --resource-group $(resourceGroup) `
        --source-location $(appLocation) `
        --output-location $(outputLocation)

      Write-Host "Deployment completed successfully!"
