trigger:
- main

variables:
- group: StaticWebToken   # Your deployment token variable group (if still needed for reference)

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent pool

steps:
# Step 1: Copy all files to artifact staging folder
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'  # Copy everything in repo
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact staging'

# Step 2: Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifact'

# Step 3: Deploy via Azure CLI (Windows-friendly)
- task: AzureCLI@2
  inputs:
    azureSubscription: '<Your Azure Service Connection Name>'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Deploy static web app from the artifact folder
      az staticwebapp deploy `
        --name <YourStaticWebAppName> `
        --resource-group <YourResourceGroup> `
        --source "$(Build.ArtifactStagingDirectory)"
  displayName: 'Deploy Static Web App via Azure CLI'
