trigger:
- main

pool:
  name: 'MyPC-AgentPool'  # Your self-hosted agent

steps:
# Step 1: Build (for static HTML, this is just an echo)
- script: echo "Building static HTML site..."
  displayName: 'Build Step'

# Step 2: Copy files to artifact staging
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Step 3: Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Step 4: Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  inputs:
    app_location: '.'                        # Path to your static site in repo
    output_location: ''                      # Leave blank for plain HTML
    azure_static_web_apps_service_connection: 'AzureStaticWebAppConnection'  # Your service connection name
  displayName: 'Deploy to Azure Static Web App'
