name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy React App to Azure Static Web Apps
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # match your local Node.js

      - name: Install dependencies
        run: npm ci
        working-directory: ./nebula-ui

      - name: Build React app
        run: npm run build
        working-directory: ./nebula-ui

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "nebula-ui"       # points to folder with package.json
          output_location: "build" # React build output
